---
# Setup authorized_keys files per user

- name: Ensure root .ssh dir
  file:
    path: "/root/.ssh"
    state: directory
    mode: 0750
  become: yes
  when: item == "root"
  with_items: "{{ ssh_users }}"

- name: Ensure root authorized_keys file
  template:
    src: authorized_keys.j2 
    dest: "/root/.ssh/authorized_keys"
    mode: 0640
  become: yes
  when: item == "root"
  with_items: "{{ ssh_users }}"

- name: Ensure ssh group
  group:
    name: ssh
    state: present
  become: yes

- name: Ensure user
  user:
    name: "{{ item }}"
    shell: /bin/bash
    groups: ssh
    append: yes
  become: yes
  when: item != "root"
  with_items: "{{ ssh_users }}"

- name: "Ensure users .ssh dir"
  file:
    path: "/home/{{ item }}/.ssh"
    state: directory
    mode: 0750
    owner: "{{ item }}"
    group: "{{ item }}"
  become: yes
  when: item != "root"
  with_items: "{{ ssh_users }}"

- name: Ensure users authorized_keys file
  template:
    src: authorized_keys.j2 
    dest: "/home/{{ item }}/.ssh/authorized_keys"
    mode: 0640
    owner: "{{ item }}"
    group: "{{ item }}"
  become: yes
  when: item != "root"
  with_items: "{{ ssh_users }}"
