---
# tasks file for ssh

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install SSH server
  yum: "name={{ ssh_package_name }} state=installed"
  when: (ssh_managed_ssh) and (ansible_os_family == "RedHat")

- name: Install SSH server
  apt: "name={{ ssh_package_name }} state=installed"
  when: (ssh_managed_ssh) and (ansible_os_family == "Debian")

- name: Ensure SSH service is running
  service:
    name: "{{ ssh_service_name }}"
    state: started
    enabled: true
  when: ssh_managed_ssh

- name: Ensure SSH banner is present
  copy:
    src: roles/ssh/files/banner
    dest: /etc/issue.ssh
    mode: 444
  when: ssh_banner

- name: Generate sshd_conf
  template: 
    src=sshd_config.j2
    dest=/etc/ssh/sshd_config
  notify: restart ssh server
  when: ssh_managed_ssh

- include: keys.yml
